Welcome to the Giskard Hub Release Notes! Stay informed about the newest features, improvements, and important changes in Giskard Hub.

Explore Release Notes
----------------------

Click on a release below to browse the release notes for that version:

.. note::
   
   The release notes for individual versions of Hub UI and Hub SDK are asynchronous. For a full overview of the changes, **please look at the release notes for the Hub UI**.
   
.. list-table::
   :header-rows: 1
   :widths: 50 50

   * - Hub UI
     - Hub SDK
   * - :doc:`/hub/ui/release_notes/2_0_0`
     - 
   * - 
     - | :doc:`/hub/sdk/release_notes/2_0_0`
       | :doc:`/hub/sdk/release_notes/2_0_1`
       | :doc:`/hub/sdk/release_notes/2_0_2`
   * - :doc:`/hub/ui/release_notes/2_0_1`
     - 
   * - 
     - | :doc:`/hub/sdk/release_notes/2_1_0`

We Value Your Feedback
----------------------

Your feedback is fundamental to the growth of Giskard Hub. If you have suggestions or encounter any issues, please contact us or submit your feedback within `our support portal <https://support.giskard.ai/>`__. Together, we can make Giskard Hub even better!